services:
  php-for-laravel:
    # jika menggunakan build
    # build: ./php${PHP_VERSION}
    # image: php-for-laravel:latest
    # jika menggunakan image
    image: ghcr.io/taufikmaulana405/docker-for-laravel:php${PHP_VERSION}
    container_name: php-for-laravel
    hostname: "php-for-laravel"
    volumes:
      - ./src:/var/www/html
      - ./php${PHP_VERSION}/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db
  db:
    image: mariadb:10.2
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx-for-laravel:
    build: ./nginx
    image: nginx-for-laravel:latest
    container_name: nginx-for-laravel
    hostname: "nginx-for-laravel"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-for-laravel
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p455w0rd