services:
  php:
    image: ghcr.io/taufikmaulana405/docker-for-laravel:php8.3
    container_name: php
    hostname: "php"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - db
  db:
    image: mariadb:10.2
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  nginx:
    image: ghcr.io/taufikmaulana405/docker-for-laravel:nginx
    container_name: nginx
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p455w0rd